# Generated by Django 4.1.2 on 2023-02-14 14:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('osm_id', models.CharField(blank=True, max_length=12, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=28, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Amenities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('osm_id', models.CharField(blank=True, max_length=12, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=28, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Buildings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('osm_id', models.CharField(blank=True, max_length=12, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=28, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Forest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoadLalitpur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('osm_id', models.CharField(blank=True, max_length=12, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=28, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ref', models.CharField(blank=True, max_length=20, null=True)),
                ('bridge', models.CharField(blank=True, max_length=1, null=True)),
                ('tunnel', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'road_lalitpur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Waterbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('osm_id', models.CharField(blank=True, max_length=12, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=28, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Waterbody',
                'managed': False,
            },
        ),
    ]
