# Generated by Django 4.1.3 on 2023-03-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SpatialAnalysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="amenities", table="amenities",),
        migrations.AlterModelTable(name="buildings", table="buildings",),
        migrations.AlterModelTable(name="forest", table="forest",),
        migrations.AlterModelTable(name="road", table="road",),
        migrations.AlterModelTable(name="waterbody", table="waterbody",),
    ]
