# Generated by Django 4.1.2 on 2023-01-26 08:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminboundary', '0002_lalitpurmetro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cluster_lead', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DisasterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DisasterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('date_event', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField()),
                ('is_closed', models.BooleanField()),
                ('source', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('startTime', models.DateTimeField()),
                ('expireTime', models.DateTimeField()),
                ('Ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminboundary.ward')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='disasterApp.rating')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='disasterApp.disastertype')),
            ],
        ),
    ]
