# Generated by Django 4.1.2 on 2023-02-26 07:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminboundary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cluster_lead', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DisasterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.FileField(blank=True, null=True, upload_to='')),
                ('type', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DisasterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('date_event', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('registered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_verified', models.BooleanField(blank=True, null=True)),
                ('is_closed', models.BooleanField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('expireTime', models.DateTimeField(blank=True, null=True)),
                ('estimatedLoss', models.IntegerField(blank=True, null=True)),
                ('InfrastructureDestroyed', models.IntegerField(blank=True, null=True)),
                ('peopleDeath', models.IntegerField(blank=True, null=True)),
                ('Ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminboundary.ward')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disasterApp.rating')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disasterApp.disastertype')),
            ],
        ),
    ]
