# Generated by Django 4.1.2 on 2023-04-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterApp', '0002_alter_disasterevent_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasterevent',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
