# Generated by Django 4.1.2 on 2023-01-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterApp', '0002_alter_disasterevent_is_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasterevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disasterevent',
            name='expireTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disasterevent',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='disasterevent',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disasterevent',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disasterevent',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
