# Generated by Django 4.1.2 on 2023-01-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterApp', '0003_alter_disasterevent_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasterevent',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disasterevent',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
