# Generated by Django 4.1.2 on 2023-02-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterApp', '0004_disasterevent_lat_disasterevent_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disastertype',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
