# Generated by Django 4.1.2 on 2023-02-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterApp', '0005_alter_disastertype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disastertype',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
