# Generated by Django 4.1.2 on 2023-02-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterApp', '0006_alter_disastertype_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disastertype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
