# Generated by Django 4.1.2 on 2023-02-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterApp', '0007_alter_disastertype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disastertype',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
