# Generated by Django 4.1.2 on 2023-02-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterApp', '0008_alter_disastertype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasterevent',
            name='InfrastructureDestroyed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disasterevent',
            name='estimatedLoss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disasterevent',
            name='peopleDeath',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
