# Generated by Django 4.1.2 on 2023-02-26 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disasterApp', '0001_initial'),
        ('adminboundary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('createdOn', models.DateTimeField()),
                ('updatedOn', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Response.inventorycategory')),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalPolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Volunters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('availability', models.BooleanField(default=True)),
                ('isdeployed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WardResponseTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deployed', models.BooleanField(default=False)),
                ('team_leader', models.CharField(max_length=100)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disasterApp.disasterevent')),
            ],
        ),
        migrations.CreateModel(
            name='WardResponseTeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Response.wardresponseteams')),
                ('volunters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Response.volunters')),
            ],
        ),
        migrations.CreateModel(
            name='MuniResponseTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('deployed', models.BooleanField(default=False)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disasterApp.disasterevent')),
            ],
        ),
        migrations.CreateModel(
            name='MuniResponseTeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipal_police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Response.municipalpolice')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Response.wardresponseteams')),
                ('volunters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Response.volunters')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryWard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('Ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminboundary.ward')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Response.inventorylist')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMunicipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Response.inventorylist')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=255)),
                ('deployed_inventory', models.IntegerField()),
                ('time_of_action', models.DateTimeField(auto_now_add=True)),
                ('logCreator', models.CharField(blank=True, max_length=255, null=True)),
                ('disaster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disasterApp.disasterevent')),
            ],
        ),
    ]
