# Generated by Django 4.1.2 on 2023-01-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Response', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='logCreator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
