# Generated by Django 4.1.2 on 2023-01-26 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disasterApp', '0001_initial'),
        ('Response', '0002_activitylog_logcreator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='disaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disasterApp.disasterevent'),
        ),
    ]
