# Generated by Django 4.1.2 on 2023-02-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Response', '0004_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
