# Generated by Django 4.1.3 on 2023-03-01 11:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lalitpurmetro",
            fields=[
                ("gid", models.AutoField(primary_key=True, serialize=False)),
                ("objectid", models.FloatField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("palika", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={"db_table": "Lalitpurmetro", "managed": False,},
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                ("gid", models.AutoField(primary_key=True, serialize=False)),
                ("ward", models.IntegerField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("number_of_disasters", models.IntegerField(blank=True, null=True)),
                (
                    "total_infrastructure_damaged",
                    models.IntegerField(blank=True, null=True),
                ),
                ("total_estimated_loss", models.FloatField(blank=True, null=True)),
                ("total_people_death", models.IntegerField(blank=True, null=True)),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=0
                    ),
                ),
            ],
            options={"db_table": "Ward", "managed": False,},
        ),
    ]
