# Generated by Django 4.1.2 on 2023-01-26 06:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.BigIntegerField()),
                ('district', models.CharField(max_length=50)),
                ('palika', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('ward', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
