# Generated by Django 4.1.3 on 2023-03-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminboundary", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="lalitpurmetro", table="lalitpurmetro",),
    ]
