# Generated by Django 4.1.2 on 2023-02-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboundary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='number_of_disasters',
            field=models.IntegerField(default=0),
        ),
    ]
