# Generated by Django 4.1.3 on 2023-03-01 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminboundary", "0002_alter_lalitpurmetro_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="ward", table="ward",),
    ]
