# Generated by Django 4.1.2 on 2023-02-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboundary', '0003_ward_total_number_of_disasters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='total_number_of_disasters',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
