# Generated by Django 4.1.2 on 2023-02-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminboundary', '0005_alter_ward_total_number_of_disasters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='total_number_of_disasters',
        ),
    ]
