# Generated by Django 4.1.2 on 2023-02-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboundary', '0007_ward_total_number_of_disasters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='total_number_of_disasters',
        ),
        migrations.AddField(
            model_name='ward',
            name='total_estimated_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ward',
            name='total_infrastructure_damaged',
            field=models.IntegerField(default=0),
        ),
    ]
