# Generated by Django 4.1.2 on 2023-02-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboundary', '0008_remove_ward_total_number_of_disasters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='total_people_death',
            field=models.IntegerField(default=0),
        ),
    ]
